services:
    php-fpm:
        container_name: app-dentist
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - Dentist-network
        depends_on:
            - db
            - redis
        restart: always

    nginx:
        container_name: nginx-dentist
        image: nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '8080:80'
        networks:
            - Dentist-network
        restart: always
        depends_on:
            - php-fpm

    db:
        container_name: db-dentist
        image: 'mysql/mysql-server:8.0'
        ports:
            - '33061:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './storage/mysql:/var/lib/mysql'
        networks:
            - Dentist-network
        restart: always

    redis:
        container_name: redis-dentist
        image: redis:alpine
        ports:
            - '6379:6379'
        command: [ "redis-server", "--appendonly", "yes" ]
        volumes:
            - './storage/redis:/data'
        restart: always
        networks:
            - Dentist-network

networks:
    Dentist-network:
        driver: bridge
